replicaCount: 2

image:
  repository: thitbobam/python-app
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub-pull-secret

env:
  APP_ENV: production

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  nodePort: 30080