replicaCount: 2
image:
  repository: thitbobam/python-app
  tag: "0.1.0"
  pullPolicy: Always # Để test thực tế trên CI/CD
env: "production"
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  nodePort: 30080