groups:
  - name: devops-case-study-alerts
    rules:
      - alert: ApplicationDown
        expr: up{job="python-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Python application is down"
          description: "Prometheus cannot scrape the Python application /metrics endpoint. Check Kubernetes Service, Pod status and application logs."

      - alert: JenkinsDown
        expr: up{job="jenkins"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Jenkins is down"
          description: "Prometheus cannot scrape Jenkins metrics endpoint. Check Jenkins container, plugin and network connectivity."

      - alert: HighApplicationErrorRate
        expr: sum(rate(flask_http_requests_total{http_status=~"5.."}[2m])) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High 5xx error rate detected"
          description: "The Flask application is returning HTTP 5xx responses. Check recent deployments, app logs and Helm history."

      - alert: HighApplicationLatency
        expr: histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le)) > 0.5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High application latency"
          description: "P95 latency is above 500ms for more than 2 minutes. Check request volume, pod health and recent changes."

      - alert: AppPodRestartDetected
        expr: sum by (pod) (increase(kube_pod_container_status_restarts_total{namespace="devops-demo", pod=~"python-app.*"}[10m])) > 0
        for: 1m
        labels:
          severity: warning
          component: kubernetes-app
        annotations:
          summary: "Python app Pod restarted"
          description: "A python-app Pod restarted in the last 10 minutes. Check kubectl logs and pod events."

      - alert: AppDeploymentUnavailable
        expr: kube_deployment_status_replicas_available{namespace="devops-demo", deployment="python-app"} < 1
        for: 2m
        labels:
          severity: critical
          component: kubernetes-app
        annotations:
          summary: "Python app has no available replicas"
          description: "Deployment python-app has less than one available replica."
