apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Kubernetes-Prometheus
    uid: k8s-prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9091
    isDefault: false